### ISSUE TITLE
Evaluation of random agent dies

### ISSUE THREAD

**Issue by dhruvbatra** [allenai/robothor-challenge#5]
> Run evaluation on random agent
> ./scripts/evaluate_train.sh

2020-02-16 01:06:18,857 [INFO] robothor_challenge - Agent action: MoveBack
2020-02-16 01:06:18,870 [INFO] robothor_challenge - Agent action: RotateRight
2020-02-16 01:06:18,883 [INFO] robothor_challenge - Agent action: Stop
2020-02-16 01:06:18,898 [INFO] robothor_challenge - Task Start id:420 scene:FloorPlan_Train1_2 target_object:Apple|+01.98|+00.77|-01.75 initial_position:{'x': 3.0, 'y': 0.910344243, 'z': -1.75} rotation:270
2020-02-16 01:06:19,135 [INFO] robothor_challenge - Agent action: Stop
Traceback (most recent call last):
  File "example_agent.py", line 17, in <module>
    r.inference()
  File "/app/robothor_challenge/__init__.py", line 86, in inference
    episode_result['success'] = simobj['visible']
TypeError: 'NoneType' object is not subscriptable

------------------
System info: Fresh GCP instance n1-standard-4 (4 vCPUs, 15 GB memory) 1 x NVIDIA Tesla P4, Ubuntu 18; nvidia drivers and nvidia-docker installed.

**Comment by ekolve** [comment]
Updated train/val.json files have been pushed to the repo which don't cause this error.
